export default {
  MATERIAL_FAMILY: 'MaterialIcons',
  FONT_AWESOME_FAMILY: 'FontAwesome',
  CHAT: 'chat',
  HOME: 'home',
  STAR: 'star',
  LOCK: 'lock-outline',
  CONTACTS: 'contacts',
  FACEBOOK: 'facebook-official',
  INSTAGRAM: 'instagram',
  TWITTER: 'twitter',
  CLOSE: 'close',
  PHONE: 'phone',
  CARET_LET: 'caret-left',
  CARET_RIGHT: 'caret-right',
};
