name: lint-ci
on:
  push:
    branches:
      - master
jobs:
  lint:
    name: lint
    runs-on: macos-latest
    steps:
      - name: git checkout
        uses: actions/checkout@v2
      - name: validate lint
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - run: yarn install
      - run: yarn lint
